#I was supposed to use turtle, but it didn't work out for me. (Debugging takes forever!!!)

import time

def bacon_should_cry():
  print("On this function, I named it def bacon_should_cry. So...")
  print("WAHHHHH!!!!! WAHHHHHH!!!!!💦")

bacon_should_cry()

time.sleep(3.0)

def bacon_should_infinite():
  print("bacon_should_infinite =") 
  time.sleep(2.0)
  print("...")
  time.sleep(0.8)
  print("please wait a sec ok")
  time.sleep(5.0)
  print("baconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbaconbacon")
  print("How many bacons are there? ∞")

bacon_should_infinite()